# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radar-admin.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("radar-admin.proto", :syntax => :proto3) do
    add_message "Query" do
      optional :user_id, :string, 1
      optional :query, :string, 2
    end
    add_message "QueryResponse" do
      oneof :content do
        optional :text, :string, 1
        optional :table, :message, 2, "QueryResponse.Table"
      end
    end
    add_message "QueryResponse.Table" do
      repeated :columns, :string, 1
      repeated :data, :message, 2, "QueryResponse.Table.Row"
    end
    add_message "QueryResponse.Table.Cell" do
      oneof :content do
        optional :text, :string, 1
        optional :number, :double, 2
        optional :date, :uint32, 3
      end
    end
    add_message "QueryResponse.Table.Row" do
      repeated :cells, :message, 1, "QueryResponse.Table.Cell"
    end
  end
end

Query = Google::Protobuf::DescriptorPool.generated_pool.lookup("Query").msgclass
QueryResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryResponse").msgclass
QueryResponse::Table = Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryResponse.Table").msgclass
QueryResponse::Table::Cell = Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryResponse.Table.Cell").msgclass
QueryResponse::Table::Row = Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryResponse.Table.Row").msgclass
