# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: radar-admin.proto for package ''

require 'grpc'
require 'radar-admin_pb'

module Admin
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Admin'

    rpc :query, Query, QueryResponse
  end

  Stub = Service.rpc_stub_class
end
